Shops: Shops
Restaurants: Restaurants
Search: Search
StyleNavigationNight: Navigation night
StyleNavigationDay: Navigation day
StyleSatelliteStreets: Satellite streets
StyleSatellite: Satellite
StyleDark: Dark
StyleLight: Light
StyleOutdoors: Outdoors
StyleStreets: Streets
CouldNotGetPosition: Could not get position
Landmark: Landmark
Close: Close

Tooltip: Tooltip
Duration: Duration
EndDate: End date
StartDate: Start date
Chart: Chart
Action: Action
Timestamp: Timestamp
Hours: Hours
DurationHours: Duration
Remarks: Remarks

StateMachineDiagram: State machine diagram
BasicEntities: Basic entities

NotAuthorized: Not authorized
LoginToAccessPlease: Please login to access this page
Statistics: Statistics
Owner: Owner
Sequence: Sequence

End: End
Start: Start
LoginForMoreDetailsPlease: Please login for more details
WelcomeTo: Welcome to
Location: Location

ChangePassword: Change password
AlreadyExists: Already exists
No: No
Yes: Yes
DemoUserAccounts: Demo user accounts
User: User
Administrator: Administrator
InvalidUrlOrRemoved: Invalid URL or resource removed
Authentication: Authentication
Or: or
Back: Back
BackToHomepage: Go back to homepage
InvalidArguments: Invalid arguments
PermissionDenied: Permission denied
PageNotFound: Page not found

PleaseAddIfNecessary: Please add if necessary
Empty: Empty
Copy: Copy
Settings: Settings
Country: Country
CountryKZ: KZ
CountryRU: RU
CountryUS: US
Language: Language
LangKz: Kazakh
LangRu: Russian
LangEn: English
Create: Create
Link: Link
Attribution: Attribution
Logo: Logo
Photo: Photo
Url: URL
Details: Details
Title: Title
RecordDeleted: Record deleted
InvalidFormData: Invalid form data
DateCreated: Date created
TimeCreated: Time created
Author: Author
SourceCode: Source code
GitHub: GitHub
EntityRelationshipDiagram: Entity relationship diagram
Documentation: Documentation
Description: Description
Name: Name
RecordEdited: Record edited
RecordAdded: Record added
Edit: Edit
DeleteAreYouSure: Are you sure you want to delete?
ConfirmPlease: Please confirm
Actions: Actions
Homepage: Home page
MenuButton: Menu button
Save: Save
Cancel: Cancel
Dele: Delete
Change: Change
Add: Add
NoData: No data
NothingToShow: Nothing to show
EmptyDataSet: Empty dataset
AccessDeniedAdminsOnly: Only administrators have access to this page. Please log in with an administrator account
LoginPlease: Please log in to access this page
Users: Users
Email: E-mail
ResetPassword: Reset password
RestoreLogin: Restore login
Password: Password
Username: Username
SignOut: Sign out
SignIn: Sign in
Home: Home
AppName: AlmaMap