Nominatim: Nominatim
Overpass: Overpass
Endpoints: Points finaux
NoGeoRegionSetYet: La région géographique n'a pas encore été établie
NoBoundingBoxSetYet: Aucune zone de délimitation n'a encore été définie
TextColor: Couleur du texte
Theme: Thème
ThemeLight: Clair
ThemeDark: Sombre
DefaultMapStyle: Style de carte par défaut
DefaultTheme: Thème par défaut
SearchByCategory: Recherche par catégorie
DisplayDifferentTypesOfPOIs: Afficher différents types de POI
LightAndDarkTheme: Thème clair et sombre
PoiClustering: Regroupement de points d'intérêt
NorthEast: Nord-est
SouthWest: Sud-ouest
North: Nord
East: Est
South: Sud
West: Ouest
Bbox: Bbox
BoundingBox: Cadre de délimitation
Style: Style
Center: Centre
Zoom: Zoom
Next: Suivant
Region: Région
City: Ville
Fixed: Fixé
Display: Affichage
GeoRegion: Géo-région
GeoArea: Zone
IssueTracking: Suivi des problèmes
GeolocationAlternativesMessageCoordinates: coordonnés
GeolocationAlternativesMessageOrThe: or the
GeolocationAlternativesMessageAddress: adresse
GeolocationAlternativesMessageSuffix: de votre emplacement
GeolocationAlternativesMessagePrefix: Alternatively, you can specify an
GeolocationStatusTimeoutUserMessage: Le délai de détermination de votre position a expiré.
GeolocationStatusUserMessage: Votre emplacement est déterminé à l'aide des capacités de géolocalisation du navigateur.
GeolocationNotSupportedUserMessage: Il semble que votre navigateur ne prend pas en charge la géolocalisation.
GeolocationStatusDisabledExploreNearby: Il semble que la géolocalisation soit désactivée, car elle est nécessaire pour explorer les objets à proximité. Veuillez activer la géolocalisation pour ce site dans les paramètres de votre navigateur.
GeolocationStatusDisabledUserMessage: Il semble que la géolocalisation soit désactivée, car elle est nécessaire pour cartographier votre position. Veuillez activer la géolocalisation pour ce site dans les paramètres de votre navigateur.
AboutYourLocation: À propos de votre emplacement
GeolocationOptions: Options de géolocalisation
Geolocation: Géolocalisation
Latitude: Latitude
Longitude: Longitude
GeolocationDisabled: La géolocalisation est désactivée
Timeout: Délai d'attente
PositionUnavailable: Position indisponible
Find: Trouver
PublicInstitutions: Institutions publiques
Parks: Parcs
Nearby: À proximité
InKilometers: in kilometers
NearbyRadius: Rayon proche de mon emplacement
Radius: Rayon
MainMenu: Menu principal
RestaurantsShopsAndMore: Restaurants, boutiques et plus
Attractions: Attractions
MapStyleOptions: Options de style de carte
Compass: Boussole
MyLocation: Mon emplacement
ZoomOut: Zoom arrière
ZoomIn: Zoom avant
ExploreNearby: Explorez les environs
NoShops: Il n'y a pas de boutiques
NoShopsWereFoundForSearchTerms: Aucune boutique contenant tous vos termes de recherche n'a été trouvée.
NoRestaurants: Il n'y a pas de restaurants
NoRestaurantsWereFoundForSearchTerms: Aucun restaurant contenant tous vos termes de recherche n'a été trouvé
ThatIsAll: C'est tout
LoadMore: Charger plus
Type: Type
Brand: Marque
ShowOnMap: Afficher sur la carte
Phone: Téléphone
OpeningHours: Horaires d'ouverture
Address: Adresse
Cuisine: Cuisine
Restaurant: Restaurant
SearchForShops: Rechercher des boutiques
SearchForRestaurants: Rechercher des restaurants
SearchByNameOrAddress: Rechercher par nom ou par adresse
SearchPlacesByNameOrAddress: Rechercher des lieux par nom ou par adresse
SearchPlacesByName: Rechercher des lieux par nom
SearchByStreetNamesAndPoi: Recherche par noms de rue et lieux d'intérêt
NoLocationsWereFound: Aucun emplacement n'a été trouvé correspondant à votre recherche
Shops: Boutiques
Restaurants: Restaurants
Search: Recherche
StyleNavigationNight: Navigation nocturne
StyleNavigationDay: Journée de navigation
StyleSatelliteStreets: Rues satellites
StyleSatellite: Satellite
StyleDark: Sombre
StyleLight: Léger
StyleOutdoors: En plein air
StyleStreets: Les rues
CouldNotGetPosition: Impossible d'obtenir la position
Landmark: Point de repère
Close: Fermer
Tooltip: Info-bulle
Duration: Durée
EndDate: Date de fin
StartDate: Date de début
Chart: Graphique
Action: Action
Timestamp: Horodatage
Hours: Heures
DurationHours: Durée
Remarks: Remarques
StateMachineDiagram: Diagramme de machine d'état
BasicEntities: Entités de base
NotAuthorized: Non autorisé
LoginToAccessPlease: Veuillez vous connecter pour accéder à cette page
Statistics: Statistiques
Owner: Propriétaire
Sequence: Séquence
End: Fin
Start: Commencer
LoginForMoreDetailsPlease: Veuillez vous connecter pour plus de détails
WelcomeTo: Bienvenue à
Location: Emplacement
ChangePassword: Changer le mot de passe
AlreadyExists: Existe déjà
No: Non
Yes: Oui
DemoUserAccounts: Comptes d'utilisateurs démo
User: Utilisateur
Administrator: Administrateur
InvalidUrlOrRemoved: URL non valide ou ressource supprimée
Authentication: Authentification
Or: ou
Back: Retour
BackToHomepage: Retour à la page d'accueil
InvalidArguments: Arguments invalides
PermissionDenied: Permission refusée
PageNotFound: Page non trouvée
PleaseAddIfNecessary: Veuillez ajouter si nécessaire
Empty: Vide
Copy: Copie
Settings: Paramètres
Country: Pays
CountryRO: RO
CountryFR: FR
CountryKZ: KZ
CountryRU: RU
CountryUS: US
Language: Langue
LangRo: Roumaine
LangFr: Française
LangKz: Kazakhe
LangRu: Russe
LangEn: Anglaise
Create: Créer
Link: Lien
Attribution: Attribution
Logo: Logo
Photo: Photo
Url: URL
Details: Détails
Title: Titre
RecordDeleted: Enregistrement supprimé
InvalidFormData: Données de formulaire non valides
DateCreated: Date de création
TimeCreated: Le temps créé
Author: Auteur
SourceCode: Code source
GitHub: GitHub
EntityRelationshipDiagram: Diagramme de relation entre entités
Documentation: Documentation
Description: Description
Name: Nom
RecordEdited: Enregistrement édité
RecordAdded: Enregistrement ajouté
Edit: Modifier
DeleteAreYouSure: Etes-vous sûr de vouloir supprimer ?
ConfirmPlease: Veuillez confirmer
Actions: Actions
Homepage: Page d'accueil
MenuButton: Bouton de menu
Save: Enregistrer
Cancel: Annuler
Dele: Supprimer
Change: Modifier
Add: Ajouter
NoData: Aucune donnée
NothingToShow: Rien à montrer
EmptyDataSet: Ensemble de données vide
AccessDeniedAdminsOnly: Seuls les administrateurs ont accès à cette page. Veuillez vous connecter avec un compte administrateur
LoginPlease: Veuillez vous connecter pour accéder à cette page
Users: Utilisateurs
Email: E-mail
ResetPassword: Réinitialiser le mot de passe
RestoreLogin: Restaurer la connexion
Password: Mot de passe
Username: Nom d'utilisateur
SignOut: Se déconnecter
SignIn: Se connecter
Home: Accueil
MetaDescription: Points d'intérêt d'OpenStreetMap sur la carte Mapbox
AppName: AlmaMap

Doc001 appname href: L'application Web <a class="link" href=#{href} target=_blank>#{appname}</a> affiche les points d'intérêt d'OpenStreetMap sur la carte Mapbox.

Doc002 href: <a class="link" href=#{href} target=_blank>Dépôt du projet</a> sur GitHub.

Doc003 href: Veuillez noter que l'application actuellement en cours d'exécution est une application de démonstration. Toutes les actions sont autorisées et encouragées. <a href=#{href} target=_blank>Signalez les bugs</a> sur GitHub.

Doc005: Intégration avec des API externes