SearchForShops: Дүкендерді іздеңіз
SearchForRestaurants: Мейрамханаларды іздеңіз
SearchByNameOrAddress: Аты немесе мекенжайы бойынша іздеңіз
SearchPlacesByNameOrAddress: Орындарды аты немесе мекенжайы бойынша іздеңіз
SearchPlacesByName: Орындарды аты бойынша іздеу
SearchByStreetNamesAndPoi: Көше атаулары мен көрікті жерлер бойынша іздеңіз
NoLocationsWereFound: Іздеуіңізге сәйкес орын табылмады
Shops: Дүкендер
Restaurants: Мейрамханалар
Search: Іздеу
StyleNavigationNight: Навигация түні
StyleNavigationDay: Навигация күні
StyleSatelliteStreets: Спутниктік көшелер
StyleSatellite: Спутник
StyleDark: Қараңғы
StyleLight: Ашық
StyleOutdoors: Сыртта
StyleStreets: Көшелер
CouldNotGetPosition: Позиция ала алмады
Landmark: Көрнекті белгі
Close: Жабу

Tooltip: Құрал кеңесі
Duration: Ұзақтығы
EndDate: Аяқталу күні
StartDate: Басталу күні
Chart: Диаграмма
Action: Әрекет
Timestamp: Уақыт белгісі
Hours: Сағат
DurationHours: Ұзақтығы
Remarks: Ескертулер

StateMachineDiagram: Күй машинасының диаграммасы
BasicEntities: Негізгі нысандар

NotAuthorized: Рұқсат етілмеген
LoginToAccessPlease: Бұл бетке кіру үшін жүйеге кіріңіз
Statistics: Статистика
Owner: Меншік иесі
Sequence: Тізбек

End: Соңы
Start: Бастау
LoginForMoreDetailsPlease: Қосымша мәліметтер алу үшін жүйеге кіріңіз
WelcomeTo: қош келдіңіз
Location: Орналасқан жері

ChangePassword: Құпия сөзді өзгерту
AlreadyExists: Қазірдің өзінде бар
No: Жоқ
Yes: Иә
DemoUserAccounts: Демо пайдаланушы тіркелгілері
User: Пайдаланушы
Administrator: Әкімші
InvalidUrlOrRemoved: Жарамсыз URL мекенжайы немесе ресурс жойылды
Authentication: Аутентификация
Or: немесе
Back: Артқа
BackToHomepage: Негізгі бетке оралу
InvalidArguments: Жарамсыз аргументтер
PermissionDenied: Рұқсат қабылданбады
PageNotFound: Бет табылмады

PleaseAddIfNecessary: Қажет болса қосыңыз
Empty: Бос
Copy: Көшіру
Settings: Параметрлер
Country: Ел
CountryKZ: KZ
CountryRU: РУ
CountryUS: АҚШ
Language: Тіл
LangKz: Қазақ
LangRu: Орыс
LangEn: Ағылшын
Create: Жасау
Link: Сілтеме
Attribution: Атрибуция
Logo: Логотип
Photo: Фото
Url: URL
Details: Мәліметтер
Title: Тақырып
RecordDeleted: Жазба жойылды
InvalidFormData: Жарамсыз пішін деректері
DateCreated: Жасалған күні
TimeCreated: Уақыт құрылды
Author: Автор
SourceCode: Бастапқы код
GitHub: GitHub
EntityRelationshipDiagram: Нысан қатынасының диаграммасы
Documentation: Құжаттама
Description: Сипаттама
Name: Аты
RecordEdited: Жазба өңделді
RecordAdded: Жазба қосылды
Edit: Өңдеу
DeleteAreYouSure: Жойғыңыз келетініне сенімдісіз бе?
ConfirmPlease: Растауыңызды өтінеміз
Actions: Әрекеттер
Homepage: Негізгі бет
MenuButton: Мәзір түймесі
Save: Сақтау
Cancel: Болдырмау
Dele: Жою
Change: Өзгерту
Add: Қосу
NoData: Деректер жоқ
NothingToShow: Көрсететін ештеңе жоқ
EmptyDataSet: Бос деректер жинағы
AccessDeniedAdminsOnly: Бұл бетке тек әкімшілер ғана кіре алады. Әкімші тіркелгісі арқылы жүйеге кіріңіз
LoginPlease: Бұл бетке кіру үшін жүйеге кіріңіз
Users: Пайдаланушылар
Email: Электрондық пошта
ResetPassword: Құпия сөзді қалпына келтіру
RestoreLogin: Жүйеге кіруді қалпына келтіру
Password: Құпия сөз
Username: Пайдаланушы аты
SignOut: Шығу
SignIn: Кіру
Home: Үй
AppName: AlmaMap