Nominatim: Nominatim
Overpass: Overpass
Endpoints: Puncte finale
NoGeoRegionSetYet: Regiunea geografică nu a fost încă stabilită
NoBoundingBoxSetYet: Încă nu a fost stabilită nicio casetă de delimitare
TextColor: Culoarea textului
Theme: Tema
ThemeLight: Luminoasă
ThemeDark: Întunecată
DefaultMapStyle: Stil de hartă implicit
DefaultTheme: Tema implicită
SearchByCategory: Căutați după categorie
DisplayDifferentTypesOfPOIs: Afișați diferite tipuri de POI
LightAndDarkTheme: Temă luminoasă și întunecată
PoiClustering: Gruparea punctelor de interes
NorthEast: Nord-est
SouthWest: Sud-vest
North: Nord
East: Est
South: Sud
West: Vest
Bbox: Bbox
BoundingBox: Casetă de delimitare
Style: Stil
Center: Centru
Zoom: Zoom
Next: Următorul
Region: Regiune
City: Oraş
Fixed: Fixat
Display: Afișare
GeoRegion: Geo-regiune
GeoArea: Zonă
IssueTracking: Urmărirea problemelor
GeolocationAlternativesMessageCoordinates: coordonate
GeolocationAlternativesMessageOrThe: sau cel
GeolocationAlternativesMessageAddress: adresa
GeolocationAlternativesMessageSuffix: a locației dvs
GeolocationAlternativesMessagePrefix: Alternativ, puteți specifica un
GeolocationStatusTimeoutUserMessage: Timpul pentru determinarea locației dvs. a expirat.
GeolocationStatusUserMessage: Locația dvs. este determinată folosind capabilitățile de geolocație ale browserului.
GeolocationNotSupportedUserMessage: Se pare că browserul dvs. nu acceptă localizarea geografică.
GeolocationStatusDisabledExploreNearby: Se pare că ați dezactivat localizarea geografică, deoarece este necesară pentru a explora obiectele din apropiere. Vă rugăm să activați geolocalizarea pentru acest site în setările browserului dvs.
GeolocationStatusDisabledUserMessage: Se pare că ați dezactivat localizarea geografică, deoarece este necesară pentru a vă mapa locația. Vă rugăm să activați geolocalizarea pentru acest site în setările browserului dvs.
AboutYourLocation: Despre locația dvs
GeolocationOptions: Opțiuni de geolocalizare
Geolocation: Geolocalizare
Latitude: Latitudine
Longitude: Longitudine
GeolocationDisabled: Geolocalizarea este dezactivată
Timeout: Timeout
PositionUnavailable: Poziție indisponibilă
Find: Găsi
PublicInstitutions: Instituţiile publice
Parks: Parcuri
Nearby: În apropiere
InKilometers: în kilometri
NearbyRadius: Raza aproape de locația mea
Radius: Rază
MainMenu: Meniul principal
RestaurantsShopsAndMore: Restaurante, magazine și multe altele
Attractions: Atracții
MapStyleOptions: Opțiuni pentru stilul hărții
Compass: Busolă
MyLocation: Locația mea
ZoomOut: Micșorați
ZoomIn: Măriți
ExploreNearby: Explorați în apropiere
NoShops: Nu există magazine
NoShopsWereFoundForSearchTerms: Nu au fost găsite magazine care să conțină toți termenii dvs. de căutare
NoRestaurants: Nu există restaurante
NoRestaurantsWereFoundForSearchTerms: Nu au fost găsite restaurante care să conțină toți termenii dvs. de căutare
ThatIsAll: Asta-i tot
LoadMore: Încarcă mai mult
Type: Tip
Brand: Marca
ShowOnMap: Arată pe hartă
Phone: Telefon
OpeningHours: Orele de deschidere
Address: Adresa
Cuisine: Bucătărie
Restaurant: Restaurant
SearchForShops: Caută magazine
SearchForRestaurants: Caută restaurante
SearchByNameOrAddress: Căutați după nume sau adresă
SearchPlacesByNameOrAddress: Căutați locuri după nume sau adresă
SearchPlacesByName: Căutați locuri după nume
SearchByStreetNamesAndPoi: Căutați după numele străzilor și locurile de interes
NoLocationsWereFound: Nu au fost găsite locații care să corespundă căutării dvs
Shops: Magazine
Restaurants: Restaurante
Search: Căutare
StyleNavigationNight: Navigație noapte
StyleNavigationDay: Navigație ziuă
StyleSatelliteStreets: Străzi satelit
StyleSatellite: Satelit
StyleDark: Întunecată
StyleLight: Luminoasă
StyleOutdoors: În aer liber
StyleStreets: Străzi
CouldNotGetPosition: Nu s-a putut obține poziția
Landmark: Reper
Close: Închide
Tooltip: Indicator
Duration: Durată
EndDate: Data de încheiere
StartDate: Data de începere
Chart: Diagramă
Action: Acţiune
Timestamp: Marca temporală
Hours: Ore
DurationHours: Durată
Remarks: Remarci
StateMachineDiagram: Diagrama mașinii de stare
BasicEntities: Entități de bază
NotAuthorized: Neautorizat
LoginToAccessPlease: Vă rugăm să vă autentificați pentru a accesa această pagină
Statistics: Statistici
Owner: Proprietar
Sequence: Secvenţă
End: Sfârşit
Start: Început
LoginForMoreDetailsPlease: Vă rugăm să vă autentificați pentru mai multe detalii
WelcomeTo: Bun venit la
Location: Locaţie
ChangePassword: Schimbaţi parola
AlreadyExists: Deja există
No: Nu
Yes: Da
DemoUserAccounts: Conturi de utilizator Demo
User: Utilizator
Administrator: Administrator
InvalidUrlOrRemoved: Adresă URL nevalidă sau resursă eliminată
Authentication: Autentificare
Or: sau
Back: Înapoi
BackToHomepage: Reveniți la pagina de pornire
InvalidArguments: Argumente nevalide
PermissionDenied: Acces refuzat
PageNotFound: Pagina nu a fost găsită
PleaseAddIfNecessary: Vă rugăm să adăugați dacă este necesar
Empty: Gol
Copy: Copiază
Settings: Setări
Country: Ţară
CountryRO: RO
CountryFR: FR
CountryKZ: KZ
CountryRU: RU
CountryUS: US
Language: Limbă
LangRo: Română
LangFr: Franceză
LangKz: Kazah
LangRu: Rusă
LangEn: Engleză
Create: Creează
Link: Link
Attribution: Atribuire
Logo: Logo
Photo: Foto
Url: URL
Details: Detalii
Title: Titlu
RecordDeleted: Înregistrare ștearsă
InvalidFormData: Date de formular nevalide
DateCreated: Data creării
TimeCreated: Timpul creării
Author: Autor
SourceCode: Codul sursă
GitHub: GitHub
EntityRelationshipDiagram: Diagrama entitate-relație
Documentation: Documentare
Description: Descriere
Name: Nume
RecordEdited: Înregistrare editată
RecordAdded: Înregistrare adăugată
Edit: Editează
DeleteAreYouSure: Sigur doriți să ștergeți?
ConfirmPlease: Vă rugăm să confirmați
Actions: Acțiuni
Homepage: Pagina de start
MenuButton: Butonul meniu
Save: Salvează
Cancel: Anulează
Dele: Şterge
Change: Schimbă
Add: Adăuga
NoData: Fără date
NothingToShow: Nimic de arătat
EmptyDataSet: Set de date gol
AccessDeniedAdminsOnly: Doar administratorii au acces la această pagină. Vă rugăm să vă conectați cu un cont de administrator
LoginPlease: Vă rugăm să vă conectați pentru a accesa această pagină
Users: Utilizatori
Email: E-mail
ResetPassword: Resetează parola
RestoreLogin: Restabiliți autentificarea
Password: Parolă
Username: Nume de utilizator
SignOut: Deconectați-vă
SignIn: Conectați-vă
Home: Acasă
MetaDescription: Puncte de interes din OpenStreetMap pe harta Mapbox
AppName: AlmaMap

Doc001 appname href: Aplicația web <a class="link" href=#{href} target=_blank>#{appname}</a> afișează punctele de interes din OpenStreetMap pe harta Mapbox.

Doc002 href: <a class="link" href=#{href} target=_blank>Depozitul de proiect</a> pe GitHub.

Doc003 href: Vă rugăm să rețineți că aplicația care rulează în prezent este o aplicație demonstrativă. Orice acțiune este permisă și încurajată. <a href=#{href} target=_blank>Raportați erori</a> pe GitHub.

Doc005: Integrare cu API-uri externe