SearchForShops: Поиск магазинов
SearchForRestaurants: Поиск ресторанов
SearchByNameOrAddress: Поиск по названию или адресу
SearchPlacesByNameOrAddress: Поиск мест по названию или адресу
SearchPlacesByName: Поиск мест по названию
SearchByStreetNamesAndPoi: Поиск по названиям улиц и интересующих мест
NoLocationsWereFound: Не найдено ни одного местоположения, соответствующего вашему запросу
Shops: Магазины
Restaurants: Рестораны
Search: Поиск
StyleNavigationNight: Ночь навигация
StyleNavigationDay: Навигация день
StyleSatelliteStreets: Улицы-спутник
StyleSatellite: Спутник
StyleDark: Темный
StyleLight: Светлый
StyleOutdoors: На улице
StyleStreets: Улицы
CouldNotGetPosition: Не удалось получить позицию
Landmark: Достопримечательность
Close: Закрыть

Tooltip: Подсказка
Duration: Продолжительность
EndDate: Дата окончания
StartDate: Дата начала
Chart: Диаграмма
Action: Действие
Timestamp: Временная метка
Hours: Часы
DurationHours: Продолжительность
Remarks: Замечания
StateMachineDiagram: Схема машины состояний

BasicEntities: Базовые сущности
NotAuthorized: Не разрешено
LoginToAccessPlease: Пожалуйста, войдите в систему, чтобы получить доступ к этой странице
Statistics: Статистика
Owner: Владелец
Sequence: Последовательность
End: Конец
Start: Начало

LoginForMoreDetailsPlease: Пожалуйста, войдите в систему для более подробной информации
WelcomeTo: Добро пожаловать на
Location: Локация

ChangePassword: Изменить пароль
AlreadyExists: Уже существует
No: Нет
Yes: Да
DemoUserAccounts: Демо-аккаунты
User: Пользователь
Administrator: Администратор
InvalidUrlOrRemoved: Неверный URL-адрес или ресурс удален
Authentication: Аутентификация
Or: или
Back: Вернуться
BackToHomepage: Вернуться на домашнюю страницу
InvalidArguments: Неверные аргументы
PermissionDenied: Доступ запрещен
PageNotFound: Страница не найдена

PleaseAddIfNecessary: Пожалуйста, добавьте, если необходимо
Empty: Пустой
Copy: Копировать
Settings: Настройки
Country: Страна
CountryKZ: Казахстан
CountryRU: Россия
CountryUS: США
Language: Язык
LangKz: Казахский
LangRu: Русский
LangEn: Английский
Create: Создать
Link: Ссылка
Attribution: Атрибуция
Logo: Логотип
Photo: Фото
Url: URL-адрес
Details: Подробности
Title: Название
RecordDeleted: Запись удалена
InvalidFormData: Неверные данные формы
DateCreated: Дата создания
TimeCreated: Время создания
Author: Автор
SourceCode: Исходный код
GitHub: GitHub
EntityRelationshipDiagram: Диаграмма взаимосвязи сущностей
Documentation: Документация
Description: Описание
Name: Имя
RecordEdited: Запись отредактирована
RecordAdded: Запись добавлена
Edit: Редактировать
DeleteAreYouSure: Вы уверены, что хотите удалить?
ConfirmPlease: Пожалуйста подтвердите
Actions: Действия
Homepage: Домашняя страница
MenuButton: Кнопка меню
Save: Сохранить
Cancel: Отмена
Dele: Удалить
Change: Изменить
Add: Добавить
NoData: Нет данных
NothingToShow: Нечего показывать
EmptyDataSet: Пустой набор данных
AccessDeniedAdminsOnly: Доступ к этой странице имеют только администраторы. Пожалуйста, войдите под учетной записью администратора
LoginPlease: Пожалуйста, войдите для доступа к этой странице
Users: Пользователи
Email: E-mail
ResetPassword: Сбросить пароль
RestoreLogin: Восстановить вход
Password: Пароль
Username: Логин
SignOut: Выйти
SignIn: Войти
Home: Главная
AppName: AlmaMap